export const Constants = {
  BASE_URL: process.env.EXPO_PUBLIC_BASE_URL,
  GOOGLE_IOS_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID,
  GOOGLE_WEB_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID,
  GOOGLE_IOS_URL_SCHEME: process.env.EXPO_PUBLIC_GOOGLE_IOS_URL_SCHEME,
  GOOGLE_MAPS_API_KEY: "AIzaSyBmInsBLw3LufW_nUALGUdhph-E_nwAPaY",
};
